name: Test Branch-Gio Github Actions
on:
  push:
    branches:
      - Branch-Gio
  pull_request:
    branches:
      - Branch-Gio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Trigger Webhook
          run: curl -X POST ${{ secrets.WEBHOOK_URL }}
    
